baseURL = 'http://yangwujie.github.io/hugo-classroom/'
languageCode = 'zh-cn'
title = 'H@pPY'
theme = ["classroom", "reveal-hugo"]

[params]
author = "杨武杰"
description = "一个试验性的教学网站"
gh_url = "https://api.github.com/users"
gh_user = "yangwujie"

[permalinks]
posts = "posts/:year/:month/:slug/"
year = "/posts/:slug/"
month = "/posts/:slug/"

[taxonomies]
year = "year"
month = "month"
tag = "tags"
category = "categories"

# for reveal-hugo
[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

